server.port=8080
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=qNvvThsLOnjBlhoJlizrAcGgMBUymWGh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.cors.allowed-origins=https://student-portfolio-production.up.railway.app,https://fsad-student-portfolio.vercel.app,http://localhost:5173
